# Generated by Django 3.0.8 on 2020-08-03 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='arp',
            new_name='mrp',
        ),
    ]
